const characters = [
    {
        name: 'Son Goku',
        img: "https://dragonball.guru/wp-content/uploads/2021/03/goku-profile-e1616173641804-400x400.png",
        desciption:'First introduced as a young boy, Son Goku (孫悟空, Son Gokū) is depicted as immensely strong, pure of heart, and extremely competitive, but dedicated to defending his adopted home Earth from internal or external threats. Although he appears human, it is later revealed that Goku is a Saiyan, and that his original name is Kakarrot.',
    },
    {
        name: 'Bulma',
        img: "https://dragonball.guru/wp-content/uploads/2021/03/bulma-profile-400x400.png",
        desciption:"Bulma (ブルマ, Buruma) first appears as a teenager using the Dragon Radar, a fictional device she created to detect the energy signal emitted by Dragon Balls. She is led to Goku's location by the signal emitted by the four-star ball in his possession and recruits him as a bodyguard while hoping to get his four-star ball to grant her wish for a boyfriend.[ch. 1] She gives up on the wish after meeting Yamcha,[ch. 23] and much later in the series, she marries Vegeta. Bulma has also assumed the role of inventor and has consistently provided critical tech support to Goku and his friends with their battles against various enemies and threats throughout the series. Some of her notable innovations include a microband that could make her shrink, and a time machine that brought her son from an alternate future timeline, Trunks, to the past on multiple occasions.",
    },
    {
        name: 'Krillin',
        img: "https://dragonball.guru/wp-content/uploads/2021/03/krillin-profile-1-400x400.png",
        desciption:"Krillin (クリリン, Kuririn) is a bald martial artist and one of Goku's best friends and classmates. He and Goku are under the tutelage of Master Roshi;[ch. 28] initially his rival but later a friend, and a loyal companion in adventures thereafter. He is killed by King Piccolo's spawn Tambourine, but is later revived by Shenron.[ch. 135, 165] After the fight with the Saiyans, he travels to Planet Namek, where he is killed by Frieza.[ch. 317] After being brought back to life again by the Namekian Dragon Balls,[ch. 329] he helps out during the Android and Cell arcs. He is married to Android 18 and has a daughter, Marron (マーロン, Māron).",
    },
    {
        name: 'Piccolo',
        img: "https://dragonball.guru/wp-content/uploads/2021/03/Piccolo-Profile-Pic-415x415.png",
        desciption:" by Goku, he must team up with him and his friends when opposing the invading Saiyans, including training Goku's son Gohan.[ch. 193, 198, 205] He is later revealed to be a Namekian—a green-skinned, four-fingered, hairless humanoid species who created the series' titular Dragon Balls.[ch. 214] He dies sacrificing himself to protect Gohan during the fight against the Saiyan Nappa, and trains in the afterlife under King Kai before being wished back to life by the Namekian Dragon Balls.[ch. 223, 261, 293] While he temporarily maintains the partnership during the fights with Frieza and the Androids, by the time of the Cell and Majin Buu arcs he accepts the fact they are allies.",
    },
    {
        name: 'Son Gohan',
        img: "https://dragonball.guru/wp-content/uploads/2021/03/toppng.com-mystic-gohan-dragon-ball-z-gohan-1021x2859-1-e1617011806816-400x400.png",
        desciption:"Son Gohan (孫悟飯) is Goku's eldest son with Chi-Chi, who first appears at the age of four.[ch. 196] He is kidnapped by Goku's brother, Raditz, and locked up in a space pod. However, his temper flares and he bursts out of the space pod, dealing a blow to Raditz and knocking himself out. After the battle, Piccolo takes and trains him for a year as he realizes Gohan's potential.[ch. 205] Gohan slowly becomes one of the strongest characters in the series, at one point holding his own against Frieza and eventually defeats Cell. After the Majin Buu arc, he marries Videl, with whom he later has a daughter named Pan",
    },
    {
        name: 'Vegeta',
        img: "https://dragonball.guru/wp-content/uploads/2021/03/vegeta-profile-400x400.png",
        desciption:"Vegeta (ベジータ, Bejīta) is the last prince of the Saiyan warrior people, and the fourth generation of the Saiyan royal bloodline to bear his namesake. He is first shown conquering a planet with his partner Nappa by listening to Raditz's fight on Earth using their scouters.[ch. 204] The two of them travel to Earth in search of the Dragon Balls, and he ends up fighting a newly revived Goku, but retreats after persistent attacks by Yajirobe, Krillin, and Gohan.[ch. 235–240] He flees to recuperate before heading off to Planet Namek to collect its Dragon Balls before Frieza can.[ch. 246] While on Namek, Vegeta proceeds to battle and kill many of Frieza's underlings. He is later forced to team up with Gohan, Goku, Piccolo, and Krillin so they can fight off Frieza. After Frieza's defeat, Vegeta lives on Earth and forms a relationship with Bulma. When the Androids arrive, it is revealed he has fathered a son with Bulma, Trunks.[ch. 337] Later in the series, he and Bulma have a younger child daughter named Bra (ブラ, Bura), known as Bulla in the English dub; unlike her father and brother, and despite being half-Saiyan, she does not show any interest in fighting.",
    },
    {
        name: 'Trunks',
        img: "https://dragonball.guru/wp-content/uploads/2021/03/Trunks-Profile-Pic.png",
        desciption:"Trunks (トランクス, Torankusu) first appears as a mysterious young man who easily defeats Frieza and his father King Cold prior to Goku's return to Earth from Planet Namek.[ch. 331, 332] It is revealed that he is Vegeta and Bulma's future child who has traveled back in time to inform Goku of the arrival of the Red Ribbon Androids that, in his time, have killed everyone else in the Dragon Team besides Goku, who died of heart disease.[ch. 334, 335] Trunks' backstory is detailed in The History of Trunks television special. He helps fight against the Androids and Cell before returning to his timeline. The character reappears in Dragon Ball Super to request assistance from the main timeline's heroes, and also appears in Super Dragon Ball Heroes.Just as the Androids arrived, the Trunks from the series' main timeline was born.[ch. 337] Seven years later as a child, Trunks, already able to turn Super Saiyan at his age,[ch. 429] fights against Majin Buu by using the fusion technique with his best friend Goten to form the composite being Gotenks (ゴテンクス, Gotenkusu)."
    },
    {
        name: 'Yamcha',
        img: "https://dragonball.guru/wp-content/uploads/2021/03/yamcha-profile-e1616269253412-400x400.png",
        desciption:"Yamcha (ヤムチャ, Yamucha), known as Zedaki in the Harmony Gold dub, is introduced as a desert bandit alongside his companion Puar, trying to steal Goku and Bulma's Dragon Balls. He becomes nervous when near women.[ch. 8, 9] He eventually becomes Goku's ally, starts a relationship with Bulma, and later becomes a pupil of Master Roshi.[ch. 23, 112] His signature attack is the Rōgafūfūken , a physical barrage of punches and palm strikes, ending with a double palm strike.[ch. 8] As a result of training under Master Roshi, Yamcha is able to perform the Kamehameha and develops the Sōkidan , an energy sphere directed by psychokinesis.[ch. 117, 175] He also later trains under Kami to prepare for the impending Saiyan invasion, but is killed by one of their Saibamen.[ch. 209, 215] Before being wished back to life by the Namekian Dragon Balls, he trained under King Kai in the afterlife.[ch. 261, 329] He remains as a regular member of the Dragon Team, but gradually becomes less active later in the series.",
    },
    {
        name: 'Tien Shinhan',
        img: "https://dragonball.guru/wp-content/uploads/2021/03/tien-e1619050541929-400x400.png",
        desciption:"Tenshinhan (天津飯テンシンハン), named Tien Shinhan in the Funimation anime dub and also known as Shinto in the Harmony Gold dub, is first introduced, having been trained by Master Roshi's rival Master Shen, trying to kill Goku and his fellow-students.[ch. 113, 129] Later, he and Chiaotzu become their allies, fighting against King Piccolo's minion until Goku arrives.[ch. 147, 154] In the fight with the Saiyans, Tien Shinhan dies of exhaustion against Nappa.[ch. 218] He trains in the afterlife under King Kai before being revived by the Namekian Dragon Balls.[ch. 261, 329] Tien Shinhan helps out during the battles against the Androids and Cell, but for the most part does not participate in fighting until Frieza's return and later the Tournament of Power.",
    },
    {
        name: 'Chiaotzu',
        img: "https://dragonball.guru/wp-content/uploads/2021/03/Chiaotzu-Profile-Pic-400x400.png",
        desciption:"Chaozu (餃子チャオズ), Chiaotzu in the English anime dub, is a small human that resembles a jiangshi with pale skin, red cheeks, and has one hair under his hat. Although he is not physically strong, Chiaotzu is skilled with psychokinesis and telepathy.[ch. 116, 121] Chiaotzu is first introduced at the 22nd World Martial Arts Tournament, having been trained by Master Roshi's rival Master Shen, trying to kill Goku and his fellow-students.[ch. 113] After Tien Shinhan decides that Master Shen's teachings are wrong, the two leave him and join Goku and his companions to defeat King Piccolo. After assisting Tien Shinhan and Master Roshi in finding the Dragon Balls, Chiaotzu is killed by King Piccolo while trying to thwart his wish for eternal youth, but is later revived using the Dragon Balls.[ch. 147, 165] In the battle against the Saiyans, he ineffectively self-destructs on Nappa in order to save Tien Shinhan.[ch. 217] He trains in the afterlife under King Kai before being revived by the Namekian Dragon Balls.[ch. 261, 329] Chiaotzu joins the other characters when they gather for Frieza's return, but Trunks kills Frieza before a fight ensues. Chiaotzu is generally no longer involved in battle from that point onwards, although he continues to train with Tien Shinhan. He is voiced by Hiroko Emori in Japanese,[18] Rebecca Forstadt in the Harmony Gold dub, Cathy Weseluck in the Ocean dub, and Monika Antonelli in Funimation's dubs, except in Kai onwards where Brina Palencia voices him.",
    },
    {
        name: 'Bardock',
        img: "https://dragonball.guru/wp-content/uploads/2021/08/Bardock-Profile-Pic-400x400.png",
        desciption:"Bardock (バーダック, Bādakku)—or Burdock in Viz's English manga translation—is the husband of Gine (ギネ), and the father of Raditz and Kakarrot (Goku). Bardock's story is first shown in the 1990 Dragon Ball Z TV special by Toei Animation, and is later retold in Toriyama's 2014 Dragon Ball Minus: The Departure of the Fated Child special and Dragon Ball Super: Broly. He also stars in the 2011 spin-off manga Dragon Ball: Episode of Bardock and its subsequent animated short film adaptation.",
    },
    {
        name: 'Android 18',
        img: "https://dragonball.guru/wp-content/uploads/2021/03/android-18-profile-pic-415x415.png",
        desciption:"Android 18 is a Red Ribbon Android created by Doctor Gero, and the sister of Android 17.[ch. 351] After being released, she travels with Androids 16 and 17 to find and kill Goku, though they are interrupted by Cell and the Dragon Team several times. She and 17 are eventually absorbed by Cell, but later during the Cell Games, a hard blow from Gohan causes Cell to regurgitate her. Although Krillin is unable to wish for her to be turned into a human, he is able to have her self-destruct device removed.[ch. 418] She settles down with Krillin, and at some point, they have a daughter named Marron (マーロン, Māron).[ch. 426, 431] 18 continues to make recurring appearances as a secondary character, and later fights for Team Universe 7 in the Tournament Of Power arc.",
    },
    {
        name: 'Son Goten',
        img: "https://dragonball.guru/wp-content/uploads/2021/03/goten-profile-pic-400x400.png",
        desciption:"Son Goten (孫悟天) is the youngest son of Goku and Chi-Chi. When first introduced, Goten strongly resembles his father in appearance with the same hairstyle and similar clothing;[ch. 424] as a teenager at the end of the series, his appearance has changed to include a shirt bearing his name and a longer, shaggier hairstyle.[ch. 518] Goten was trained by his older brother Gohan in preparation for the 25th World Martial Arts Tournament, which their father attended. During the training, Gohan discovers Goten is already quite strong, as he has been training with their mother (compared to Gohan's childhood), and can become a Super Saiyan despite still being a child.[ch. 427] Like several characters in the series, he can also perform the Kamehameha technique.[ch. 434] In order to save the world from Majin Buu, Goku and Piccolo teach Goten and Trunks the fusion technique, which allows them to form a single being, Gotenks (ゴテンクス, Gotenkusu).[ch. 480] Gotenks battles Buu multiple times but he is unable to defeat Buu even as a Super Saiyan 3. Buu temporarily absorbs Gotenks to increase his own power, but Vegeta and Goku are able to retrieve him from Buu. When Buu destroys the Earth, Goten and Trunks are killed.[ch. 506] The Dragon Balls later bring Goten back to life along with the rest of the Earth in order to give energy to Goku's Genki-Dama attack, which defeats Buu.[ch. 514] Goten and Trunks appear as the protagonists of the eleventh Dragon Ball Z feature movie, Bio-Broly. Goten is one of the most popular characters in the series. Japanese fans voted Goten the sixth most popular character of the Dragon Ball series in a 2004 poll.[20] Goten is ranked number 13 on IGN's Top 13 Dragon Ball Z Characters List,[21] and came in 6th place on Complex.com's list A Ranking of All the Characters on 'Dragon Ball Z'; Sheldon Pearce notes that the character exists mostly as part of a pair with Trunks, who is the more assertive member of the duo, and their bond makes them extremely compatible to undergo the fusion technique.[22]Masako Nozawa voices Goten in Japanese,[23] while he is voiced by Kara Edwards (as a child) and Robert McCollum (as a teen) in the Funimation dub. He is also voiced by Dana Hayes in the Bang Zoom! Entertainment dub.",
    },
    {
        name: 'Broly',
        img: "https://dragonball.guru/wp-content/uploads/2021/07/broly-profile-pic-400x400.png",
        desciption:"Broly (ブロリー, Burorī) is the main villain in the films Dragon Ball Z: Broly – The Legendary Super Saiyan and Broly – Second Coming. He is depicted to be born with a power greater than most elite adult Saiyans, and is mentally unstable as an adult. He eventually becomes the Legendary Super Saiyan (伝説の超サイヤ人, Densetsu no Chō Saiya-jin) spoken of in legends, with his destructive tendencies only being quelled by a special controlling device created by scientists for his father, Paragus (パラガス, Paragasu).A different version of Broly appears in the animated film Dragon Ball Super: Broly, whose backstory and physical appearance have been personally reworked by Toriyama and integrated into the series canon continuity.",
    },
    {
        name: 'Son Pan',
        img: "https://dragonball.guru/wp-content/uploads/2021/03/Pan-Dragon-Ball-Super-Super-Hero-Profile-School-Uniform-415x415.png",
        desciption:"Pan (パン) is Goku's granddaughter and Gohan and Videl's daughter.[ch. 518] She appears as a young child in the final installments of the original manga and the Dragon Ball Z anime series. In Dragon Ball Z: Battle of Gods film and Dragon Ball Super, Videl, pregnant with Pan, volunteers for a ritual on behalf of her unborn daughter as a sixth Saiyan participant is required. In Japanese media she is voiced by Yūko Minaguchi.[64] In the English versions of Dragon Ball Z, she is voiced by Brenna O'Brien in the Ocean dub and Kate Bristol in the Funimation dub. In the English-language adaptations of Dragon Ball GT, she is voiced by Caitlynne Medrek in the Blue Water dub, with Mariette Sluyter voicing her as an elder, and Elise Baughman voices her in the Funimation dub. Baby/Little Pan is voiced by Jeannie Tirado in Super.",
    },
]
export default characters;